### PR TITLE
fix(library view): fix #710 unable to change library type if library …

### LINKED ISSUE #710: Changing library type to an empty one locks you in
**Describe The Bug**

When changing the library type (like switching to genres or collection in a movie lib) and it the chosen type is empty, it'll lock you in.

**Steps To Reproduce**

https://user-images.githubusercontent.com/1619359/107658940-f19dcc00-6c86-11eb-8871-9d423163cbb6.mp4

### PR DESCRIPTION
**Pull request by Camc314**
…is empty

Re enables type-button, filter-button when length is 0

Edit: fix #710

### CODE REVIEW

File: pages/library/_viewId.vue [hunk 1]
```diff
@@ -29,7 +29,7 @@
       <filter-button
         v-if="isSortable"
         :collection-info="collectionInfo"
-        :disabled="loading || !items.length"
+        :disabled="loading"
```
Comment (ThibaultNocchi) [inline pages/library/_viewId.vue:32]: I don't think filter have to be re-enabled in that case, if we have nothing to filter ^^

**Review by ThibaultNocchi — CHANGES_REQUESTED** [review]

File: pages/library/_viewId.vue (hunk 1 above)
Comment (Camc314) [reply pages/library/_viewId.vue:32]: If we are in a library, and apply a range of filters, such that there are no items, we can't unfiltered to show the items again.

Comment (ThibaultNocchi) [reply pages/library/_viewId.vue:32]: Nice catch!

**Review by ThibaultNocchi — APPROVED** [review]

**Comment by ThibaultNocchi** [comment]
fix #710

File: pages/library/_viewId.vue (hunk 1 above)
Comment (ferferga) [reply pages/library/_viewId.vue:32]: @Camc314 I that case I think we should keep a track of the original (unfiltered array) and check for that. Right now with what you did is possible to use filters in a library that has no items.
