### PR TITLE
fix: properly disconnect user when server is unreachable

### LINKED ISSUE #1929: Can't reset client when auto-reconnecting to a user with a server not responding
### Description of the bug

If you load the page with a user already connected to a server not responding, there's no way to go to the "add server" page. You can log out (with a bad UI though) and get stuck in the user picker page from the unresponsive server. And there, you can manually go to /server/add by changing the URL, but that's all.

### Steps to reproduce

- Login with a user with the "remember me" set to ON
- Close the page
- Stops the JF server
- Opens the page

### Expected behavior

It should logout the user and redirect to the /server/add page.

### Logs

_No response_

### Screenshots

_No response_

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.9

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ThibaultNocchi**
fix #1929

### CODE REVIEW

File: frontend/src/pages/server/login.vue [hunk 1]
```diff
@@ -68,19 +68,27 @@ import { isEmpty } from 'lodash-es';
...
 const route = useRoute();
+const router = useRouter();
 const remote = useRemote();
 const api = remote.sdk.oneTimeSetup(
   remote.auth.currentServer?.PublicAddress || ''
 );
 
 route.meta.title = t('login.login');
 
+try {
```
Comment (ferferga) [inline frontend/src/pages/server/login.vue:86]: Why is this needed here? Doesn't the interceptor catches this already?

Comment (ThibaultNocchi) [reply frontend/src/pages/server/login.vue:86]: Nope, cause in this case it doesn't get a 401, just a NET_ETROR from Axios, hence the interceptor doing nothing and just throwing the error.

**Review by ferferga — APPROVED** [review]
